### ISSUE TITLE
[Suggestion] Per tab instructions on Documentation

### ISSUE THREAD

**Issue by frenchiveruti** [HandBrake/HandBrake-docs#10]
Hi!, I would like to suggest that each tab that the program has when someone encodes, has it's own page, instead of an "objective" wiki, where it tells you how to do what, a "focus" wiki, where each page talks about a part of the program, in this case the Tabs.
For example, lets take the "Picture" tab:
"Here you can set the image size of your encode, and crop it."
And an explanation per line in display:
"Source" The size WxH of the source file you've selected.
"Width""Height" The size in pixels of the **OUTPUT**, you can use the "anamorphic" for the settings around this.

And so on.
Thanks. Any questions feel free to reply here.
Great software.

**Comment by bradleysepos** [comment]
Thanks for the suggestions.

The old wiki documentation was organized in this fashion, focusing on the application's various buttons and "knobs", so to speak. Unfortunately, it was very difficult for non-technical people to follow. This project is more focused on workflow, or objectives, as you suggest; this is on purpose. That said, there is a technical section which we will be adding more to over time, and I think that will serve your needs.

Note also that as of HandBrake 1.0.0, all tooltips (helpful information displayed when you hover your mouse cursor over a control) in HandBrake for Mac have been rewritten. Similar efforts are currently underway to bring the Linux and Windows tooltips up to date for all controls. I think you'll find this very helpful; it's exactly what you suggest, in the application itself!

Thanks again for the suggestions, and feel free to comment further if need be.
