### ISSUE TITLE
Add device selection flag to NVENC Documentation

### ISSUE THREAD

**Issue by kenthklui** [HandBrake/HandBrake-docs#103]
According to this https://github.com/HandBrake/HandBrake/issues/2598 from the official Handbrake repo, selection of the NVENC device can be done through adding advanced flags such as `gpu=0`, `gpu=1` etc. This is very useful for users who are using multiple GPUs.

Unfortunately, this option does not appear under the official Handbrake documentation for Nvidia Nvenc at https://handbrake.fr/docs/en/latest/technical/video-nvenc.html . It took some digging for me to find it in the official Handbrake repo's issues.

Please add it in the table!

**Comment by bradleysepos** [comment]
Will do, thanks for the suggestion. 😸

**Comment by bradleysepos** [comment]
I've updated and revised the documented options for both AMD VCE and Nvidia Nvenc hardware encoders. Will be live the next time the docs are generated and published. Thanks for the report. 😸
