### ISSUE TITLE
v1.3.1 Linux version about page close button w/o function

### ISSUE THREAD

**Issue by Marc-Bender** [HandBrake/HandBrake-docs#104]
I got the v1.3.1 from the offical ppa as recommended and the close button in the about page does absolutely nothing...
![grafik](https://user-images.githubusercontent.com/48416871/79689307-32d67280-8254-11ea-8d18-b2469555c8f6.png)

**Comment by Marc-Bender** [comment]
edit: oops wrong repo... regardless...

**Comment by bradleysepos** [comment]
No worries. This is a known issue (GTK bug): https://github.com/HandBrake/HandBrake/issues/2405
