### ISSUE TITLE
GUI H.264 parameters for constant bitrate?

### ISSUE THREAD

**Issue by ShortRouter** [HandBrake/HandBrake-docs#105]
Hi, I'm having trouble trying to set GUI parameters for H.264 to encode using constant bitrate. Since there is no option for that in the GUI, I assume I have to use some parameters. Was able to find 
`ffmpeg -i input.mp4 -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 6M -minrate 6M -maxrate 6M -bufsize 2M output.ts`
From: https://trac.ffmpeg.org/wiki/Encode/H.264
How do I use that in the GUI as additional parameters? My aim is to convert lossless video files with H.264 encoder and it has to be 6 Mbit constant bitrate. Other settings I set in the GUI: same as source framerate, constant framerate, average bitrate 6000 (I want that to be CONSTANT 6 Mbit), preset veryfast, profile:high, level:auto
Using the Handbrake CLI is very cumbersome as I am not familiar with ffmpeg on such technical level. I also need to batch encode lots of files and using different h264 presets (veryfast, fast, medium). Please help. 
edit: I am well aware of disadvantages using CBR. I am doing streaming quality research and trying to simulate OBS H264 streaming with 6 Mbit CBR in Handbrake which later will be used for VMAF calculations.

**Comment by bradleysepos** [comment]
This is the documentation repository. Consider posting your question on the [HandBrake Community Forums](https://forum.handbrake.fr/) or for reproducible bugs, create an issue on the [HandBrake repository](https://github.com/HandBrake/HandBrake/issues).

Short answer: HandBrake is not an FFmpeg front end, and it supports ABR in the graphical interfaces. You'll almost definitely get a more thorough response with potential solutions on the forums.
