### ISSUE TITLE
Windows Explorer Properties Incorrect after Handbrake Editing

### ISSUE THREAD

**Issue by TheRiehmer** [HandBrake/HandBrake-docs#106]
I am trying to edit a video for Instagram that requires a 4:5 aspect ratio.  In Handbrake, I imported my source video that 1920 x 1080 (black edges).  I customized the size and removed 528 from left and right.  My final project looks like 864 x 1080.  In Windows Explorer post Handbrake, the Frame Width & Height still shows 1920 x 1080 on the new file details.  The new file appears to be 864 x 1080, but won't load into Instagram because the dimensions are incorrectly invalid.

![Handbrake File Properties](https://user-images.githubusercontent.com/64274990/80236279-8cf28180-8620-11ea-8cef-592ae68db8b6.png)

When Handbrake writes the new file, I think it should update the file properties to the new dimensions.

**Comment by sr55** [comment]
HandBrakes output is correct.

I suspect that either: 
1. You are using anamorphic in which case, even after cropping, the values above are correct.
2. Are dealing with a bug in the windows demuxer or whatever 3rd party demuxers you have installed. 


I suspect it's option 1 but since you failed to provide the requested activity log, we can't say any more than that.

**Comment by TheRiehmer** [comment]
I am a complete non-professional.  I just need the black sides trimmed off of a video file.  I think I found out what Handbrake is doing in this print screen:

![Handbrake File Properties2](https://user-images.githubusercontent.com/64274990/80238274-c5478f00-8623-11ea-9639-666e1abadbb4.png)

Handbrake is storing the file at 1920 x 1080, but the display is 864 x 1078.  I guess I need a program that also stores the file at 864 x 1080...

**Comment by sr55** [comment]
Option 1 it is then.

This is actually correct. Anything other than 1920x1080 would be invalid and result in the file not playing correctly. 

On the dimensions tab, Set anamorphic to None and make sure Keep AR is checked. That'll have the desired effect.

**Comment by sr55** [comment]
p.s I just noticed this is also the issue tracker for HandBrakes documentation, not HandBrake app.  This is why you won't have seen the post template or guidance to post the log.

**Comment by TheRiehmer** [comment]
Thank you very much for your help!
