### ISSUE TITLE
is it possible to set subtitle 's color and font?

### ISSUE THREAD

**Issue by creatxrgithub** [HandBrake/HandBrake-docs#107]
is it possible to set subtitle 's color and font?

when i convert from .vob files, the subtitle 's color is black.
i want to change the color to white.
it seems that it has problem for some DVD, in my case, it always stop in several seconds.
so, i have to convert film by select DVD 's .vob file.
thanks

**Comment by sr55** [comment]
First, this is the issue tracker for HandBrakes documentation, not HandBrake.  Please make sure you are on the HandBrake project before raising issues.

To answer your question anyway, no, it's not possible.  Vobsubs are images and can not be altered by HandBrake.
