### ISSUE TITLE
Wrong translation for "Open Source" in Spanish

### ISSUE THREAD

**Issue by LuisPeregrinaPSL** [HandBrake/HandBrake-docs#110]
The "Open source" text, as in an action ("Open the source file") is translated in Spanish as the noun "Open source" as in "Open source software". Currently is translated as "Código abierto" and it should be "Abrir fuente" ("Abrir el archivo fuente"= "Open the source file")

**Comment by bradleysepos** [comment]
Assigning @Nomis101 as this seems to be related to the UI translation and not documentation.

@LuisPeregrinaPSL Thanks for identifying this issue. If you'd like to help with translating HandBrake, we'd love to have you onboard our Transifex project. Please read https://github.com/HandBrake/HandBrake/blob/master/TRANSLATION.markdown and fill out https://github.com/HandBrake/HandBrake/issues/new?template=translate_request.md if you'd like to help directly. Thanks!

**Comment by Nomis101** [comment]
Interesting. I haven't seen that one. I think this must be the same like https://github.com/HandBrake/HandBrake/issues/2961
Is it also fine if it is translated as "Abrir Origen", which is the current status on Transifex?

**Comment by LuisPeregrinaPSL** [comment]
Yup, it's the same. I see that one got completed, we can close this one.
@bradleysepos it got denied. Couldn't enter transifex.

**Comment by Nomis101** [comment]
> @bradleysepos it got denied. Couldn't enter transifex.

It seems this was me then. Did you open a Translation Team request on GitHub or only send a request on Transifex? The normal process is to deny all incomplete requests. The Translation Team request is important, because I need your name on Transifex to accept the correct person. If you send a new request on Transifex and write here your Transifex user name, I think it will also be fine to accept you request.

**Comment by frenchiveruti** [comment]
I sent a request for fixing this on transifex, is such an awful translation it hurts.

**Comment by Nomis101** [comment]
> I sent a request for fixing this on transifex, is such an awful translation that it hurts.

Thanks for your request to improve the Spanish translation. I have accepted your join request on Transifex. You can now start to localize and improve the strings.
