### ISSUE TITLE
Does HandBrake do audio?

### ISSUE THREAD

**Issue by seamusdemora** [HandBrake/HandBrake-docs#111]
I came to HandBrake via [this link](https://github.com/amiaopensource/ffmpeg-amia-wiki/wiki/3)-Graphical-User-Interface-Applications-using-FFmpeg). It implies tat HandBrake is a GUI "front-end" for `ffmpeg` - which is what I eas looking for. 

But after spending a few minutes browsing some of the docs, I can find nothing about processing ***audio*** files - the reason I use ffmpeg! 

Does HandBrake do audio - or is it just a "part-time" GUI for `ffmpeg`?

**Comment by bradleysepos** [comment]
Your link appears to be broken.

That said, HandBrake uses FFmpeg for some functionality, but is not strictly an FFmpeg front-end. HandBrake is video-focused and is not intended for audio use alone. If you're looking for a graphical audio application, perhaps consider Audacity?

**Comment by bradleysepos** [comment]
It looks like this is the link in question: https://github.com/amiaopensource/ffmpeg-amia-wiki/wiki/3%29-Graphical-User-Interface-Applications-using-FFmpeg

I would definitely say that article is a bit misleading, but not technically wrong in that HandBrake is a graphical application that does use FFmpeg for certain things. The HandBrake-is-an-FFmpeg-front-end rumor has really been picking up steam the last year or two for unknown reasons. 🤷‍♂️

**Comment by seamusdemora** [comment]
@bradleysepos : Apologies for the bum link, but yes - I think you found the one I intended to use. And thanks for the clarification... I've used HandBrake for a while & I *thought* it was "video only". When I saw the reference claiming it was a GUI for ffmpeg, I wondered if I had missed something. I didn't see it of course, but decided to ask the question "just to be sure". :)

**Comment by 01y** [comment]
Speaking as a user, having a "none" or "(null)" option added to the "Video Encoder:" selection drop-down would be very useful, especially for extracting non-video tracks on a DVD, without having to spend time and computer resources on a video encode that will simply be immediately discarded.
