### ISSUE TITLE
How can I start pt-BR language on the docs section?

### ISSUE THREAD

**Issue by victorwestmann** [HandBrake/HandBrake-docs#112]
Hi Peeps, I hope you are all surviving this apocalyptic period we are all living. Whit that being said, how can I start the pt-BR language in the documentation chapter of the amazing handbrake application?

Thank you!
Victor

**Comment by bradleysepos** [comment]
In short, duplicate `source/en/1.3.0` as `source/pt/1.3.0` (or `source/pt-br/1.3.0` if your translation will be Brazil-specific; I'm not knowledgeable about how significant the differences between pt and pt-BR are) and start translating the articles. When you've made significant progress we can merge your changes. https://github.com/HandBrake/HandBrake-docs/blob/master/CONTRIBUTING.markdown has some helpful info and I'll be glad to assist further as needed.

Thanks for your interest. 😸

**Comment by victorwestmann** [comment]
Thank you brother! I would say that pt-BR and pt-PT differ around 25 - 30% and is 70% similar. Thank you for your directions. Will translate the UI first and then jump to the docs. Thanks!

**Comment by bradleysepos** [comment]
`source/pt-BR/1.3.0` will be fine, then. Thanks!
