### ISSUE TITLE
Developer - CentOS 7 nasm update

### ISSUE THREAD

**Issue by sei-jmattson** [HandBrake/HandBrake-docs#113]
Hey there, looks like you are dropping centos7 in latest; understandable with all the dependency work-arounds.

The write-up for centos7 works great, but recently nasm published an incompatible rpm to their `stable` repo. (It requires `rpmlib(PayloadIsZstd)` which 7 won't get.)

I saw the nasm requirement is >=2.13, so I used their previous release from https://www.nasm.us/pub/nasm/releasebuilds/2.14/linux/, but maybe not worth updating docs.

    yum install https://www.nasm.us/pub/nasm/releasebuilds/2.14/linux/nasm-2.14-0.fc27.x86_64.rpm

Thanks for great docs!

**Comment by bradleysepos** [comment]
Nice catch, will update the 1.3.x docs with your solution soon. What is the first nasm version to have the issue?

> Thanks for great docs!

A kind word goes a long way after a rough week. Thank *you*.

**Comment by sei-jmattson** [comment]
It looks like nasm only puts the latest release in their `stable` repo.  2.15 just dropped a couple weeks ago.  2.14 was the previous release a year and half prior, so I assume that's what you got when you tested/updated the docs 4 months ago.

Anyway, I used 2.14 from the releasebuilds folder of their repo, and it worked fine.

**Comment by bradleysepos** [comment]
My goodness, it took too long for me to get back to this. What a year. Should be good to go now in 3d3b8f744576bfbf7081a2bbe55cd79610428911. Thanks again. 😸
