### ISSUE TITLE
Greater pressure on the NVENC Chip VS Quality

### ISSUE THREAD

**Issue by jemar100** [HandBrake/HandBrake-docs#116]
Hello how are you? I write this section because I use this program to reduce the size of all the movies that I download from the web. In turn, I have an NVIDIA card specifically 970 GTX FTW (EVGA), when I use the video codec focused on NVENC technology, the result is unsatisfactory if not horrible.
So, my intention with this post is to ask if someone can put some command lines to use in the Advanced Options box that can, let's say, modify for the better the quality / size of the resulting file, since something I must limit is that when I use the codeg H.264 or H.265 NVENC card only works about 10%, maybe more or maybe less.
I would like to try to squeeze even more the card and not so much the CPU. Now if there are no command lines for this request that I am talking about.
Is there any way in which the 10-bit and 12-bit (x265) codecs respectively try through the command line to reduce some of the heavy work of the CPU and move it to VGA?
 I await your answers ....

**Comment by sr55** [comment]
Please be aware, Github is not a support medium.   We recommend the community forums over on handbrake.fr for such questions.


We already document the very limited number of options for NVEnc in the docs but at the end of the day, all you can really do is move the quality slider to the right until you find the desired quality level, at the expense of filesize.  NVEnc is not capable of matching x264 in this regard. Especially on older cards like the 970.

x265 is a software implementation of hevc/h265. It does not use the GPU.    There is no 10/12bit support for the hardware encoders available in HandBrake.

**Comment by jemar100** [comment]
Thanks friend ...iam sorry for post...
