### ISSUE TITLE
Is it possible tp insert keyframes in a video ?

### ISSUE THREAD

**Issue by vinodvinu** [HandBrake/HandBrake-docs#117]
Hi,
I want to insert key frames in every 50 frames. Currently my video contains key frames in every 250 frames. So seeking is quite difficult. Is it possible with Handbrake ?

**Comment by bradleysepos** [comment]
Yes, you can, but only by re-encoding the entire video, which HandBrake does. Take a look at the Production Standard preset. You probably don't want the large files it will make, but the additional options on the video tab show how to control key frame allocation for the x264 encoder.

Specifically, `keyint=12:min-keyint=1` means insert a key frame at least every 12 frames, or more frequently based on scene changes. You probably want `keyint=50:min-keyint=1` and can add this to any of the presets in the General category or others using the x264 video encoder.

**Comment by vinodvinu** [comment]
@bradleysepos ,
Thanks for the detailed reply. And sorry for the delayed response. Let me try this. Anyways, i have succeeded the same with  ffmpeg. But it takes 12 minutes to complete a 45 mins video. So, i want to find a better solution.

**Comment by bradleysepos** [comment]
As this is the documentation issue tracker, please ask further questions on one of our community support channels. Thanks. 😸
