### ISSUE TITLE
qBittorrent presets

### ISSUE THREAD

**Issue by tanner11** [HandBrake/HandBrake-docs#12]
A really useful feature would be the ability to set the maximum bit rates for both audio and video.

My friends and I encode our movies at 160 audio and 900 video, anything less and "pass" is the obvious choice.
It would be nice to set maximums that would automatically fall back to pass if less than the maximum setting.
The same way width and height maximums work.

Thanks,

Regards,

Bill,

**Comment by bradleysepos** [comment]
If you'd like to request changes to HandBrake, please do so on the main HandBrake issue tracker (this one tracks documentation-specific issues).

HandBrake always re-encodes video. While it would potentially be useful to only re-encode audio if the source bitrate was sufficiently high, this is a fairly niche feature that is low on the priority list to implement. Your general application seems a bit niche as well, so you are probably best off creating a custom preset using ABR mode for the video.
