### ISSUE TITLE
Multiple VOB files into one MP4 file

### ISSUE THREAD

**Issue by ClivePickering** [HandBrake/HandBrake-docs#120]
Hi, is it possible to combine multiple VOB files from a DVD into a single MP4 file? Thanks. Clive.

**Comment by bradleysepos** [comment]
HandBrake does not merge multiple inputs. If the IFO files are present, they define the DVD structure and the entire VIDEO_TS or parent directory should be opened using HandBrake. You can also encode individual clips with the same settings and combine them using MKVToolNix or similar.

As this is the documentation issue tracker, please ask further questions on one of our [community support channels](https://handbrake.fr/community.php). Thanks. 😸
