### ISSUE TITLE
Incorrect section headers in documentation

### ISSUE THREAD

**Issue by drmandarin** [HandBrake/HandBrake-docs#125]
In the current [HandBrake documentation](https://handbrake.fr/docs/en/1.3.0/), section headers under "Technical Documentation" are incorrect and internally inconsistent.

First please see:
Technical Documentation » Hardware encoders » Nvidia Nvenc
As a reference, the header "Supported Hardware and Configurations" is correct, because the content relates to both hardware and configurations.

Now see the incorrect entries:
Technical Documentation » Hardware encoders » AMD VCE
Under the header "Supported hardware":
Ubuntu Linux 18.04.3 or later, Windows 10
These are not hardware.
The header should be renamed "Supported Hardware and Configurations".

Technical Documentation » Hardware encoders » Intel QuickSync Video
Under the header "Supported hardware":
Windows 10
Linux
These are not hardware.
The header should be renamed "Supported Hardware and Configurations".

**Comment by bradleysepos** [comment]
Should be fixed now. Thanks.
