### ISSUE TITLE
"Nvenc" in documentation is incorrectly written

### ISSUE THREAD

**Issue by drmandarin** [HandBrake/HandBrake-docs#126]
In the [HandBrake documentation](https://handbrake.fr/docs/en/1.3.0/) (and also possibly in the relevant text in the application), "Nvenc" is incorrect.
This is [correctly written](https://developer.nvidia.com/nvidia-video-codec-SDK) "NVENC".

**Comment by bradleysepos** [comment]
Thanks, this is fixed by the same commits addressing #125.
