### ISSUE TITLE
X-TIMESTAMP-MAP

### ISSUE THREAD

**Issue by DDHF22** [HandBrake/HandBrake-docs#128]
Any chance that Handbrake would process .srt entries like these 

X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

correctly ? - Or at least allow us to ignore them. Right now they just appear as ordinary subtitle text.

Thanks

**Comment by bradleysepos** [comment]
I'm guessing you meant to post on https://github.com/HandBrake/HandBrake/issues (this is the documentation project). If you want to open an issue there, please give us some more info on what those entries are intended to do.

**Comment by DDHF22** [comment]
My appologies - I wil repost.
