### ISSUE TITLE
Need a way to turn off automatic cropping as a defualt.

### ISSUE THREAD

**Issue by jamesparksart** [HandBrake/HandBrake-docs#129]
I am the head video production artist at my company and your tool is awesome at compression.. but most of our videos have some blank space or we leave parts of our videos black on purpose. This causes the "Automatic" cropping to always try and crop it and I always have to go in and manually adjust it. I don't know for sure, but There should be a "Set as Default" button on that page so that if you want it to always be 1920 x 1080 and Autocropping off. You just set it up and then click save as default or something. It is really un-productive to have to go and adjust the cropping every time.  Thank you!

**Comment by bradleysepos** [comment]
This is the issue tracker for the documentation project (main project: https://github.com/HandBrake/HandBrake/issues/).

That said, it's easy to set this up. Make your changes, then save a new HandBrake preset with the name of your choice. Make sure your new preset is selected, and use the Preset menu to set it as the default. Now HandBrake will use your settings every time unless you select something different.
