### ISSUE TITLE
missing functions?

### ISSUE THREAD

**Issue by idanka** [HandBrake/HandBrake-docs#131]
1. Fedora 34 install rpmfusion missing h265 NVEnc (or not work)
2. Fedora 34 install flatpak missing h264 NVEnc (or not work)
3. Ubuntu 20.04.2 install snap missing NVEnc (or not work)
4. Ubuntu install  official releases PPA h264 convert error
5. Ubuntu Building HandBrake for Linux NVEnc h264 sound slips, no sync

Howto uninstall Building HandBrake?

"Install HandBrake (optional). When installing the graphical interface, icon and desktop files for the Applications menu will be also installed.
sudo make --directory=build install"

**Comment by sr55** [comment]
replace install with uninstall   
or simply remove the files.

We do not support builds provided by distros, rpmfusion, snap, ppa and you should not use these as they are provided by 3rd parties and in an unknown state.

NVEnc will only be available on supported hardware, using the official NVidia proprietary driver and is considered experimental on Linux so your mileage may vary.
