### ISSUE TITLE
How to build Handbrake using llvm-12 suite, clang-12, ld.lld-12 with LTO on Linux?

### ISSUE THREAD

**Issue by StatusCode404** [HandBrake/HandBrake-docs#135]
Hi Experts,
As the title suggests,...How to build Handbrake using llvm-12 suite, clang-12, ld.lld-12 with LTO on Linux?

I have the three sets installed on Ubuntu 18.04 and can successfully build Linux using llvm-12 suite, clang-12, and ld.lld-12 with thin LTO and O3 along with march/mtune=native.

How do I do the same with Handbrake?  The make process is quite different to building linux.

Thanks in advance!

**Comment by sr55** [comment]
This is not supported yet.

This may be of interest.  https://github.com/HandBrake/HandBrake/pull/3927
