### ISSUE TITLE
Without cropping SUP subtitle

### ISSUE THREAD

**Issue by Atom2004** [HandBrake/HandBrake-docs#136]
Enable auto cropping of the video an got an Top and Bottom cropping like that
![image](https://user-images.githubusercontent.com/22042246/123551592-16618e80-d7a5-11eb-88be-e5d09d50c54d.png)

Mean while add an SUP subtitle in the *.ts file.

The subtitle show like this
![image](https://user-images.githubusercontent.com/22042246/123552029-e4e9c280-d7a6-11eb-9079-cfd227dcf10c.png)

I think the perfect perform is like this (check the BURN IN)
![image](https://user-images.githubusercontent.com/22042246/123552103-342ff300-d7a7-11eb-8082-54bd1a12399d.png)

But BURN-IN build the subtitle into the picture not a subtitle track.
![image](https://user-images.githubusercontent.com/22042246/123552082-182c5180-d7a7-11eb-88b2-f35fa8c3c2d6.png)

**Comment by sr55** [comment]
This is the documentation issue tracker. Not the HandBrake app issue tracker.

HandBrake app issues can be posted here: https://github.com/HandBrake/HandBrake/issues/

That said, this is possibly  https://github.com/HandBrake/HandBrake/issues/2847
