### ISSUE TITLE
DRC only relevant to AC3?

### ISSUE THREAD

**Issue by inspector71** [HandBrake/HandBrake-docs#14]
If DRC is only relevant to AC3 sources then why is the option enabled for other formats? Would it not be more user friendly to disable the DRC option for non-AC3 formats?

**Comment by bradleysepos** [comment]
Please provide an [Activity Log](https://handbrake.fr/docs/en/1.0.0/help/activity-log.html). It will be helpful to know what system we're talking about.

**Comment by bradleysepos** [comment]
Oops, thought this was on the main HandBrake issue tracker. DRC appears to be properly disabled for non-AC3 on Mac. It seems you may have found a bug on one of the other graphical interfaces. Please open a new issue there: https://github.com/HandBrake/HandBrake/issues
