### ISSUE TITLE
HandBrakeCli  --encopts="gpu=0" didn't change anything

### ISSUE THREAD

**Issue by Hoax017** [HandBrake/HandBrake-docs#140]
I use this command :
`    HandBrakeCLI -i %fullpath% -o %fullpathout% -m -E copy –audio-copy-mask ac3,dts,dtshd –audio-fallback ffac3 -e x264 -q 20 -x ref=6:subq=7:trellis=0:bframes=3:b-adapt=2:direct=auto:me=umh:merange=16:analyse=all:open-gop=0:rc-lookahead=50:level=4.1:no-fast-pskip=1:no-mixed-refs=0:no-weightb=0:no-mbtree=0:gpu=0  --encopts="gpu=0"
`

I tried to put `--encopts="gpu=0"` at the end and just `:gpu=0` in -x option and it nothing change

![image](https://user-images.githubusercontent.com/8215575/129390022-bff85ccb-7e83-497a-aab7-f59e2f66c522.png)

version :
![image](https://user-images.githubusercontent.com/8215575/129390432-81827583-1dc6-4de3-9453-71c8c1ca2724.png)

**Comment by Rodeo314** [comment]
This is not the place to report HandBrake issues, this repository is for issues with the *documentation* instead.

HandBrake issues go here: https://github.com/HandBrake/HandBrake/issues

**Comment by Hoax017** [comment]
> 
> 
> This is not the place to report HandBrake issues, this repository is for issues with the _documentation_ instead.
> 
> HandBrake issues go here: https://github.com/HandBrake/HandBrake/issues

I don't know if i use it correctly due to documentation

**Comment by sr55** [comment]
Documentation for 3rd party encoders is not provided by us.  You'd need to lookup the x264 documentation for their available options.  

What I will tell you is, there will be no GPU usage with x264 as it doesn't use the GPU for encoding.
gpu= is not a valid option for that encoder.
