### ISSUE TITLE
Troubleshooting common issues - Windows - .NET-Download broken

### ISSUE THREAD

**Issue by Jakllp** [HandBrake/HandBrake-docs#149]
I was looking for the correct version of .NET for handbrake and discovered that the link is broken (404)

**Comment by sr55** [comment]
Please see https://forum.handbrake.fr/viewtopic.php?t=41511

What link did you use that provided a 404?

**Comment by Jakllp** [comment]
https://github.com/HandBrake/HandBrake-docs/blob/master/source/docs/en/1.3.0/help/troubleshooting-common-issues.markdown?plain=1#L85

This one

**Comment by sr55** [comment]
Thanks.  I've committed an update for the "Latest" version of the documentation which will deploy to the site in the near future.

We won't be updating the 1.3 documentation as it's simply too much of a burden to keep all the older versions up-to-date. If your running an older version you'll need to google for the latest version of the link for Framework on the microsoft site.
