### ISSUE TITLE
Audio auto passthrough doesn't seem to work

### ISSUE THREAD

**Issue by adamf663** [HandBrake/HandBrake-docs#151]
In the audio settings, I have selected 'English' and checked off several passthrough, and saved the preset.
However, when loading a movie and using the saved preset, ghb defaults to no audio at all.  I've had to manually add an audio track and then select the passthrough option for it.   'Add all' does nothing; maybe that's a clue to what is going on.

**Comment by galad87** [comment]
You might want to open an issue on the HandBrake repository, this one here is only for the docs.
