### ISSUE TITLE
Custom preset doesn't remember scaled size

### ISSUE THREAD

**Issue by dilemmax** [HandBrake/HandBrake-docs#153]
I am trying to convert some vertical videos from 3840x2160 to 1920x1080. When I save the custom preset, it doesn't remember the scaled size. In this instance, when I reload the preset, the scaled size is changed to 2160x2160 (I've set the resolution limit to 2160p).

**Comment by sr55** [comment]
This is the correct behaviour. Scaled size depends on the source, thus, is not part of the preset. 

When you save a preset, set the mac to 1080p if that's what you want. 

Also, please note that this is the documentation issue tracker, not HandBrake issue tracker.  If you have questions, you can use https://github.com/HandBrake/HandBrake/discussions or want to report a bug: https://github.com/HandBrake/HandBrake/issues
