### ISSUE TITLE
Handbrake doesn't work in Chrome

### ISSUE THREAD

**Issue by Nabukodonosor** [HandBrake/HandBrake-docs#159]
Hey guys. Anyone knows why Handbrake doesn't work in chrome? Only in Firefox, and that's without ssl certificate. I've installed mine in docker.

http://prntscr.com/26rhdl4

After this I get error:
http://prntscr.com/26rhe40

**Comment by bradleysepos** [comment]
Are you by chance referring to https://github.com/jlesage/docker-handbrake? That is a separate project not maintained by us; you should ask there.

Also, this is the Documentation repository. 😸

**Comment by Nabukodonosor** [comment]
Thanks, will do.
