### ISSUE TITLE
Subtitles auto-conversion

### ISSUE THREAD

**Issue by Seegras** [HandBrake/HandBrake-docs#16]
Why are you converting SRT subtitles automatically to SSA/ASS? It's rude. You should at least provide an option to have them just passed trough. 

Not everyone likes SSA/ASS, because it's abused for "hard" positioning the subtitles, usually somewhere over the movie even if there would be blank space below.

**Comment by jstebbins** [comment]
It's not rude.  It's what was easiest.  I would like to add an SRT output option at some point, but I have an enormous TODO list and not enough time.

It is relatively easy to use mkvmerge (or it's gui mmg) to add your SRT file to the mkv after encoding with HandBrake if you require SRT subtitles.

**Comment by sr55** [comment]
This is not an issue with the HandBrake Documentation. Closing off.

There is an open enhancement request under https://github.com/HandBrake/HandBrake/issues/160 that can be used to track if/when this enahncement is add.

Thanks
