### ISSUE TITLE
Enhancement: add rating to replacement strings

### ISSUE THREAD

**Issue by YerCodeSmellsFunny** [HandBrake/HandBrake-docs#161]
First of all: thanks for making this awesome software!

Some people can't stand how bizarrely slow and problematic retrieving rating and tags metadata for videos is, for instance, on Windows explorer- and said data doesn't get cached at all.  So it takes "forever" for the OS to re-read the rating data for a medium sized directory (notion of medium scaling with one's notion of forever, obviously.)  Suffice to say, having that info baked into the filename is game-changer; such that sorting by filename also sorts the number of stars in the rating.  (I wouldn't be surprised if some people also wanted the aspect ratio, but that doesn't matter much to me.)  

I haven't sniffed your code yet so I don't know if you even have access to this data, or if "passing it through" just means providing a flag to ffmpeg.  I seem to recall ffprobe having access to the data, but I looked again and couldn't find it

**Comment by bradleysepos** [comment]
This issue seems better suited for the [HandBrake repository's issue tracker](https://github.com/HandBrake/HandBrake/issues) (this is the documentation repository). There are a number of open issues regarding metadata there, so I'm not sure whether it's a duplicate.
