### ISSUE TITLE
Documentation - Automatic File Naming

### ISSUE THREAD

**Issue by Neilisin** [HandBrake/HandBrake-docs#163]
Hi guys, the documentation is somewhat vague when it comes to the placeholder fields. 
For example: {date}  what format is that and can we choose?  Is it ISO 8601 by default or a custom or natural locale date format (hyphenated or continuous and serialised)? 

Does it have further configurations? {date-YY} {date-MM} {date-DD} {date-HH} {date-mm} etc?  

Thanks for the great work!

**Comment by sr55** [comment]
>what format is that and can we choose 

System Short Format with any "/" replaced by "-" to avoid filename conflicts.

>Does it have further configurations?  
Nope

**Comment by bradleysepos** [comment]
@sr55 Shall we close now that you've added 92838ce229892f393af01918ddc070c041fdc3c7 or did you have more you wish to accomplish there?
