### ISSUE TITLE
Documentation - build instructions for Ubuntu and QSV support

### ISSUE THREAD

**Issue by makzdot** [HandBrake/HandBrake-docs#164]
Hi,

I had trouble getting QuickSync working on Ubuntu (Same probably goes for Debian as well) After some tinkering I found the following packages missing form the build instructions on https://handbrake.fr/docs/en/latest/developer/install-dependencies-ubuntu.html

I needed to install these packages before building HandBrake:
- libmfx-dev
- libmfx1

So, if these packages could be added to the instructions, that would be great!

Regards,
Makz

**Comment by bradleysepos** [comment]
IIRC this was an issue with linking to system mfx instead of the provided mfx, and should now be resolved. If not, we can always reopen this.
