### ISSUE TITLE
Build (for Windows) not possible on VM with the instructions --> result: FAILURE (code 2)

### ISSUE THREAD

**Issue by RokE03** [HandBrake/HandBrake-docs#166]
Hi, together.

From a short while I can't build Handbrake anymore with the instructions from [here](https://handbrake.fr/docs/en/latest/developer/build-windows.html) on a **VM** with the **newest** ubuntu anymore.
Before I could do that with no issues whatsoever.

1) The instructions are not up-to-date anymore regarding the _python_ package: The package does not exist anymore, so I presume it has to be updated to _python3_ ?

2) Even with _python3_ installed, I now always get following result:
[...]
```
  : config.status: executing depfiles commands
  : touch contrib/libogg/.stamp.libogg.configure
-------------------------------------------------------------------------------
time end: Tue Aug  2 11:28:19 2022
duration: 7 seconds (7.32s)
result: FAILURE (code 2)
```

VM-Software: Virtualbox (latest) with guest extensions enabled
Linux-Distro: Ubuntu (latest)
PC with Ryzen 3900X and RTX 3080, Virtualization enabled

**Comment by RokE03** [comment]
Hi, thanks for the quick reply.

The fact that the documentation is not up-to-date unfortunately doesn't help with my build process.
I had already found the dependencies site and tried to experiment with it, but the build still fails.

If you wish, I can set up a completely new VM with the latest ubuntu and verify your documentation for the build process.
In the worst case, there is still something missing, cause it is not reproducible.

**Comment by RokE03** [comment]
Ok, I set up a new VM to verify that I did everything according to the existent documentation.

1) Downloaded latest ubuntu desktop iso
2) Setup a new VM (10 Cores, 12GB RAM, 35GB DiskSpace) on my NVME SSD
3) Went to [ubuntu dependencies](https://handbrake.fr/docs/en/latest/developer/install-dependencies-ubuntu.html) and tried to do the mentioned steps
--> Well, on the last step of this site the pkg-manager threw an error:
      `libegl-mesa0 : Depends from : libgm1 (22.0.1-1ubuntu2) but 22.0.5-0ubuntu0.1 should be installed`

Could this be the problem already? Or want me to continue?

Kind regards

**Comment by bradleysepos** [comment]
That's interesting. Are you building with QSV support? It wasn't long ago I set up a VM and updated the docs, but I believe the build was with `--disable-qsv`?

Please paste the output of your `./configure ...` command.

**Comment by RokE03** [comment]
You got a good feeling: The `--disable-qsv` option let the build process make it way more far.

Build process ran **perfectly** now. The logs are attached for your information.

I presume the QuickSync-Support breaks the Build process at least for now then?

Kind regards 

Attachments:
[build.txt](https://github.com/HandBrake/HandBrake-docs/files/9243329/build.txt)
[config.info.txt](https://github.com/HandBrake/HandBrake-docs/files/9243330/config.info.txt)
[config.verbose.txt](https://github.com/HandBrake/HandBrake-docs/files/9243331/config.verbose.txt)

**Comment by bradleysepos** [comment]
Thanks, things are starting to make sense. I suspect the issue is related to https://github.com/HandBrake/HandBrake/issues/4374, for which we are working on a fix.

**Comment by RokE03** [comment]
Yeah, could be absolutely. Thanks for your help in that matter - I'll wait then, until that issue is solved to build my Handbrake again, since I need the QuickSync-Support.

Last question:
Do you want me to let this issue open, until the documentation is updated?
Or do you want me to close it?

Kind regards

**Comment by bradleysepos** [comment]
We can leave it open. With any luck I'll get to the documentation issue in a few days. I have some time planned for QSV as well so we'll hopefully have the other issue resolved swiftly.

**Comment by RokE03** [comment]
Hi. Was the issue with building Handbrake with Quicksync-Support resolved?

I did a new build just now **without** "--disable-qsv" and it worked.

Kind regards

**Comment by bradleysepos** [comment]
I believe this is now resolved. If that is not the case for someone, we can always reopen.
