### ISSUE TITLE
Missing NVENC option on Ubuntu 22.04

### ISSUE THREAD

**Issue by PratterFak** [HandBrake/HandBrake-docs#167]
I recently updated from Ubuntu 20.04 where I was using the NVENC option. After my update to Ubuntu 22.04.1 LTS, the NVENC option is no longer available on Handbrake 1.5.1 (x86_64). Is this something that will be added again on a future update?

I'm using a Geforce GTX 780Ti with NVIDIA driver version 470.141.03
X Server 11.0
The X.Org Foundation
Server vendor version 1.21.1.3
NV-Control 1.29

**Comment by sr55** [comment]
Please note, this is the HandBrake Documentation Issue Tracker.  HandBrake issues can be raised at https://github.com/HandBrake/HandBrake/  either as an Issue or Discussion Board question.

HandBrake doesn't support the 700 series Nvidia cards. Only 10-series and later.  Linux support is considered experimental only so I'm afraid your on your own with this. 

As far as I know, there 9 series and earlier is problematic and/or non-functional on Windows so I wouldn't expect much on the Linux side either.
