### ISSUE TITLE
The quality slider behavior doesn't seem to match the documentation on Silicon Mac using VideoToolbox

### ISSUE THREAD

**Issue by GCustom** [HandBrake/HandBrake-docs#168]
Using Constant Quality, lower numbers give worse quality, higher numbers give higher quality, the recommended ranges don't look great, and even with much higher numbers it's tough to get smoke or fog not to look blocky. Using M1 Max and the latest public releases of MacOS and Handbrake for Mac. I've found 50 to be my best compromise for 1080p and 4K and out of laziness I keep it there for DVD releases too but they could use further tweaking.

**Comment by bradleysepos** [comment]
@galad87 Perhaps you could take a look at this when you have time?

**Comment by galad87** [comment]
I don't think we have any recommendation for VideoToolbox, only for x264/x265, where are you seeing this in the docs?

**Comment by GCustom** [comment]
HandBrake Documentation — Adjusting quality<https://handbrake.fr/docs/en/latest/workflow/adjust-quality.html>
I’m using the H.265 (VideoToolbox) encoder, similar results but faster progress and larger files with H.264

From: Damiano Galassi ***@***.***>
Date: Tuesday, August 30, 2022 at 00:12
To: HandBrake/HandBrake-docs ***@***.***>
Cc: GCustom ***@***.***>, Author ***@***.***>
Subject: Re: [HandBrake/HandBrake-docs] The quality slider behavior doesn't seem to match the documentation on Silicon Mac using VideoToolbox (Issue #168)

I don't think we have any recommendation for VideoToolbox, only for x264/x265, where are you seeing this in the docs?

**Comment by galad87** [comment]
That page talks only about x264 and x265. Each encoder has got a different range/direction, and VideoToolbox goes from 0 (lower quality) to 100 (max quality).
