### ISSUE TITLE
overheat GPU 

### ISSUE THREAD

**Issue by philivy** [HandBrake/HandBrake-docs#169]
hello , 
I used handbrake to change x264 to x265 video on ubuntu 20.04. 
handbrake run 100% CPU and seems to use GPU too. My 730GT GPU overheat at 95° and shutdown system. Does The application use GPU function too ? 
thanks for your answer

**Comment by sr55** [comment]
Please note, this is the HandBrake documentation issue tracker. It's not a HandBrake support forum. 

Nope. The 730GT is not used. You have a hardware cooling issue you need to resolve. That's not something we can support you with.
