### ISSUE TITLE
Release PPA unavailable

### ISSUE THREAD

**Issue by rm369** [HandBrake/HandBrake-docs#171]
On https://handbrake.fr/docs/en/1.0.0/get-handbrake/where-to-get-handbrake.html the links to https://launchpad.net/~stebbins/+archive/ubuntu/handbrake-releases lead for me to the error message

> Not allowed here
> Sorry, you don't have permission to access this page or the information in this page is not shared with you.

Do you still offer an Ubuntu release PPA or only the flatpak on the Download page?

**Comment by sr55** [comment]
PPA is no longer supported. Old releases are still present but no longer supported.

Also note, your reading the version 1.0 documentation. You can get to the latest version of the documentation here:  https://handbrake.fr/docs/
