### ISSUE TITLE
Supported hardware for QSV needs updating

### ISSUE THREAD

**Issue by X-m7** [HandBrake/HandBrake-docs#184]
According to the Intel Quick Sync Video page of the HandBrake documentation (https://handbrake.fr/docs/en/latest/technical/video-qsv.html) the minimum supported hardware is "Intel Skylake (6th Generation Core) CPU or later with Intel HD Graphics or better", however a developer stated [here](https://github.com/HandBrake/HandBrake/issues/4768#issuecomment-1367497470) that support for 6th gen hardware was dropped for 1.6.

And indeed with 1.6 with my Intel Core i7-6700HQ the QSV option disappeared, so the new minimum needs to be updated.

**Comment by sr55** [comment]
I mis-spoke.  6th gen and newer is supported. 5th gen and earlier is not.

That said, whether you can find a supported driver for older hardware is sometimes a problem. Some OEM's customise the drivers and don't provide updates. In those cases your basically out of luck if you can't install the pure Intel version.

**Comment by X-m7** [comment]
Ah, I'm on Arch Linux, and looking further into the issue I see that a fix is supposed to be coming for 1.6.1, so I guess the docs are fine.
