### ISSUE TITLE
Handbrake running for hours but never ends

### ISSUE THREAD

**Issue by piadam** [HandBrake/HandBrake-docs#185]
On MacOS I have been using HandBrake (now at Version 20230118094856-61d7fc051-master (2023012101)) to convert hundreds of TV-recordings (.ts-files) into .m4v-files.
A few days ago however HandBrake (command-line version as well as the GUI-one) seemed to not be able to finish it's process. This happened on 11.7.3 (Big Sur) as well as on 13.1 (Ventura). It happened on 2 different files, of which 1 is no longer available.

I will try to include the failing file as well as 4 screenshots, of which the 2nd one never changes...
<img width="997" alt="Screenshot 2023-01-21 at 15 15 55" src="https://user-images.githubusercontent.com/2383586/213872286-24abb831-833f-4a29-b97f-0305a1cc8cae.png">
<img width="1470" alt="Screenshot 2023-01-21 at 15 47 45" src="https://user-images.githubusercontent.com/2383586/213872288-05059109-eb5b-450b-998d-b9839161b723.png">
<img width="887" alt="Screenshot 2023-01-21 at 15 48 22" src="https://user-images.githubusercontent.com/2383586/213872294-9c45922b-4bf4-4026-afc6-bd44900f9f19.png">
<img width="857" alt="Screenshot 2023-01-21 at 15 48 48" src="https://user-images.githubusercontent.com/2383586/213872299-edad94d1-5669-44b9-9e0b-d7df60564cbc.png">

The 3rd screendump indicates that quitting HandBrake, when it said 100%, it says that quitting will terminate the process.

The 4rd dump shows a top-window, showing the CPU-load of the still running handbrake.

Oops, the movie-file is too big. I will keep it available for you for deugging. Just let me know where to send it to (it's 5GB in size).

Kind regards,
Adam

**Comment by chrysle** [comment]
Maybe you should open that issue in the [main HandBrake repository](https://github.com/HandBrake/HandBrake)?

**Comment by piadam** [comment]
Oh, OK, thanks for pointing me there... Seems like I posted this in the Handbrake Docs environment. Sorry.

**Comment by piadam** [comment]
I moved my report to the other repo.
