### ISSUE TITLE
Documentation - Please update changes to presets in 1.6.1

### ISSUE THREAD

**Issue by spencerross** [HandBrake/HandBrake-docs#187]
I just updated to Handbrake 1.6.1 and noticed there was no "Discord" preset in the "Web" category.

The documentation (https://handbrake.fr/docs/en/latest/technical/official-presets.html) shows that the Discord preset and other presets are available for selection, but it seems they have been combined into "Social" "Email" and "Creator" presets. Please update the documentation to reflect this change!

**Comment by bradleysepos** [comment]
This has been on my list for awhile. Hoping to get this updated over the weekend. Sorry for the inconvenience, and thanks for the nudge. 😸

**Comment by bradleysepos** [comment]
For reference, the descriptions of these two pull requests have basic explanations of the presets changes in 1.6.x, including how the former `Discord` presets map to the new `Social` presets:

https://github.com/HandBrake/HandBrake/pull/3919
https://github.com/HandBrake/HandBrake/pull/4757

**Comment by bradleysepos** [comment]
Time to close out this one, as I updated the presets article a couple weeks ago: https://handbrake.fr/docs/en/1.6.0/technical/official-presets.html
