### ISSUE TITLE
DCP With XYZ Color Space Conversion to YUV (Dithered 8-Bit?)

### ISSUE THREAD

**Issue by HDMOVIESOURCE** [HandBrake/HandBrake-docs#188]
Hi,

I've been discussing with somebody who takes DCP trailers and encodes them into prores.  The prores takes the XYZ color space and converts it to YUV. From what I see it looks to do this perfectly using Resolve.

However, if you encode the same DCP file with XYZ color space using Handbrake, it converts the color space to YUV, but (from what I see), it looks dithered at 8-bit and now banding is visible.

Is it possible to allow XYZ color space when converted to YUV to be lossless or another way of saying this is to not to lose bit-depth by the conversion?

The prores file converts this color space perfectly, then you encode that on Handbrake and it looks perfect, but encoding the DCP XMF file actually looks worse, and that's the original source. 

Any chance this could be improved when converting a color space to YUV from XYZ?

Thank you.

**Comment by galad87** [comment]
This repository is only for the docs, if you still have an issue please open one on the right repository.
