### ISSUE TITLE
Audio/Video out of sync Version 1.0.7 (2017040900) - 64bit

### ISSUE THREAD

**Issue by James-W2** [HandBrake/HandBrake-docs#19]
I've been using Version 0.10.5.0 - 64bit to convert MPEG2 to MP4 video, using the normal profile.  This has been working well.  However, when the latest update was announced, I upgraded to 1.0.7 (2017040900) - 64bit.  Since then, after the above conversion process, using WMP the audio and video have been out of sync by 2-3 seconds or more.  However, when I reinstalled the old version, I no longer had this sync problem.  Appears changes in the new version have caused this sync issue with WMP (and possibly other video players).  I think this issue deserves further study, as I was blaming the player for the problem rather than the new version of HandBrake.  

Attached are logs using both versions as noted above.
[Coronation Street (recorded Apr 14, 2017, Old HB)-1.m4v 5-31-2017 8-59-38 PM.txt](https://github.com/HandBrake/HandBrake-docs/files/1043736/Coronation.Street.recorded.Apr.14.2017.Old.HB.-1.m4v.5-31-2017.8-59-38.PM.txt)
[Coronation Street (recorded Apr 14, 2017, Cbutdt)-1.m4v 05-31-2017 19-19-37.txt](https://github.com/HandBrake/HandBrake-docs/files/1043738/Coronation.Street.recorded.Apr.14.2017.Cbutdt.-1.m4v.05-31-2017.19-19-37.txt)

**Comment by bradleysepos** [comment]
Please follow up on the HandBrake issue: https://github.com/HandBrake/HandBrake/issues/752

This project is exclusively for documentation. Thanks.
