### ISSUE TITLE
Typo - Docs > English > HandBrake Latest > Automatic File Naming

### ISSUE THREAD

**Issue by WizardKnight** [HandBrake/HandBrake-docs#191]
Preset is listed twice in the table for your documentation. 
https://handbrake.fr/docs/en/latest/technical/automatic-file-naming.html

<html><body>

preset | The name of the currently selected preset | Supported | Supported | Supported
-- | -- | -- | -- | --
width | The storage width of the output file | Supported | Supported | Supported
height | The height width of the output file | Supported | Supported | Supported
preset | The name of the currently selected preset | Supported | Supported | Supported

</body>
</html>

**Comment by galad87** [comment]
Remove, thanks.
