### ISSUE TITLE
building from source HandBrake 1.6.1 with ubuntu 23.04  fails to "make install"

### ISSUE THREAD

**Issue by OriKovacsiKatz** [HandBrake/HandBrake-docs#194]
when performing the "make install" step getting an error 
(base) ori***@*******:~/Public/workSWDev/HandBrake$ sudo make --directory=build install
make: Entering directory '/home/orik/Public/workSWDev/HandBrake/build'
../libhb/module.defs:49: extraneous text after 'ifeq' directive
/usr/bin/cp ./HandBrakeCLI /usr/local/bin/HandBrakeCLI
/usr/bin/cp: cannot stat './HandBrakeCLI': No such file or directory
make: *** [../test/module.rules:33: test.install] Error 1
make: Leaving directory '/home/ori****/Public/workSWDev/HandBrake/build'
(base) ori***@*******:~/Public/workSWDev/HandBrake$ cd /usr/local/bin/

apparently make file is not formed to create the folder HandBrakeCLI on /usr/local/bin/
before the copying line...

how to fix the makefile?

Also some warnings regarding naming of NUMA incorrectly Numa
with config script : ./configure --launch-jobs=$(nproc) --launch --enable-qsv
  : CMake Warning (dev) at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  :   The package name passed to `find_package_handle_standard_args` (NUMA) does
  :   not match the name of the calling package (Numa).  This can lead to
  :   problems in calling code that expects `find_package` result variables
  :   (e.g., `_FOUND`) to follow a certain pattern.
  : Call Stack (most recent call first):
  :   cmake/FindNuma.cmake:43 (find_package_handle_standard_args)
  :   CMakeLists.txt:109 (find_package)
  : This warning is for project developers.  Use -Wno-dev to suppress it.

Thanks
Ori Kovacsi-Katz

**Comment by galad87** [comment]
This repository is only for the docs, if you still have an issue please open one on the right repository.
