### ISSUE TITLE
V 1.0.7 not handling queued ISO files correctly

### ISSUE THREAD

**Issue by MrOllyK** [HandBrake/HandBrake-docs#20]
Handbrake will process the first ISO file in the queue correctly but fails with error 3 on the subsequent file, even when the ISO is unencrypted or uncorrupted. Manual handling of ISO files is only option for now - unless someone knows of a workaround?

Logfile as follows:
--------------------
HandBrake 1.0.7 (2017040900) - 64bit
OS: Microsoft Windows NT 6.1.7601 Service Pack 1 - 64bit
CPU: Intel(R) Core(TM)2 Duo CPU     T9900  @ 3.06GHz
Ram: 8152 MB, 
GPU Information:
  Mobile Intel(R) 4 Series Express Chipset Family - 8.15.10.2869
  Mobile Intel(R) 4 Series Express Chipset Family - 8.15.10.2869
Screen: 1366x768
Temp Dir: C:\Users\Olly\AppData\Local\Temp\
Install Dir: F:\Program Files\HandBrake
Data Dir: C:\Users\Olly\AppData\Roaming\HandBrake Team\HandBrake\1.0.7.0

-------------------------------------------

# Starting Encode ...

[22:08:51] hb_init: starting libhb thread
[22:08:51] 1 job(s) to process
[22:08:51] json job:
{
  "Audio": {
    "AudioList": [
      {
        "Bitrate": 192,
        "DRC": 0.0,
        "Encoder": 65536,
        "Gain": 0.0,
        "Mixdown": 4,
        "NormalizeMixLevel": false,
        "Samplerate": 48000,
        "Track": 0,
        "DitherMethod": 0
      }
    ],
    "CopyMask": [
      1073807360,
      1073743872,
      1074003968,
      1073750016,
      1090519040,
      1074790400,
      1074266112,
      1107296256
    ],
    "FallbackEncoder": 65536
  },
  "Destination": {
    "ChapterList": [],
    "ChapterMarkers": false,
    "File": "I:\\Life-2.mp4",
    "Mp4Options": {
      "IpodAtom": false,
      "Mp4Optimize": false
    },
    "Mux": 131072
  },
  "Filters": {
    "FilterList": [
      {
        "ID": 11,
        "Settings": {
          "crop-bottom": "72",
          "crop-left": "0",
          "crop-right": "0",
          "crop-top": "72",
          "height": "432",
          "width": "720"
        }
      },
      {
        "ID": 6,
        "Settings": {
          "mode": "1"
        }
      }
    ]
  },
  "PAR": {
    "Num": 64,
    "Den": 45
  },
  "Metadata": {},
  "SequenceID": 0,
  "Source": {
    "Angle": 1,
    "Range": {
      "Type": "chapter",
      "Start": 1,
      "End": 1
    },
    "Title": 2,
    "Path": "F:\\FFOutput\\LIFE.ISO"
  },
  "Subtitle": {
    "Search": {
      "Burn": true,
      "Default": false,
      "Enable": true,
      "Forced": true
    },
    "SubtitleList": []
  },
  "Video": {
    "Encoder": 65536,
    "Level": "3.1",
    "TwoPass": false,
    "Turbo": false,
    "ColorMatrixCode": 0,
    "Options": "",
    "Preset": "ultrafast",
    "Profile": "high",
    "Quality": 16.0,
    "Tune": "animation",
    "OpenCL": false,
    "HWDecode": false,
    "QSV": {
      "Decode": false,
      "AsyncDepth": 0
    }
  }
}
[22:08:51] CPU: Intel(R) Core(TM)2 Duo CPU     T9900  @ 3.06GHz
[22:08:51]  - logical processor count: 2
[22:08:51] Intel Quick Sync Video support: no
[22:08:51] hb_scan: path=F:\FFOutput\LIFE.ISO, title_index=2
src/libbluray/disc/disc.c:352: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:352: error opening file BDMV\BACKUP\index.bdmv
[22:08:51] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 5.0.1
libdvdread: Encrypted DVD support unavailable.
*** Zero check failed in src/ifo_read.c:570
    for vmgi_mat->zero_3 = 0x00000000010000000000000000000000000000
libdvdnav: DVD Title: LIFE
libdvdnav: DVD Serial Number: 00CAF144DVDSHRNK
libdvdnav: DVD Title (Alternative):
libdvdnav: DVD disk reports itself with Region mask 0x00000000. Regions: 1 2 3 4 5 6 7 8
libdvdread: Encrypted DVD support unavailable.
*** Zero check failed in src/ifo_read.c:570
    for vmgi_mat->zero_3 = 0x00000000010000000000000000000000000000
[22:08:51] scan: DVD has 1 title(s)
[22:08:51] scan: scanning title 2
[22:08:51] Invalid VTS (title set) number: 0
[22:08:51] libhb: scan thread found 0 valid title(s)
[22:08:51] libhb: work result = 3

# Encode Completed ...

**Comment by bradleysepos** [comment]
This issue tracker is for the HandBrake Documentation project. You should open a new issue on the HandBrake issue tracker here: https://github.com/HandBrake/HandBrake/issues/
