### ISSUE TITLE
Add Direct Remuxing Feature for Container Format Changes

### ISSUE THREAD

**Issue by Kiaana** [HandBrake/HandBrake-docs#206]
**Feature Request:**
I am proposing the addition of a direct remuxing feature in HandBrake that would allow users to change the container format of a video file without re-encoding the video or audio streams.

**Rationale:**
Currently, HandBrake does not provide an option to simply remux the media stream into a different container format. Users who wish to change a file from, say, MKV to MP4 without altering the encoding have to resort to other tools like FFmpeg. Adding a remuxing feature would streamline the process and make HandBrake a more comprehensive tool for video file manipulation.

**Possible Implementation:**
This could be implemented as a checkbox or a dropdown menu within the existing UI, perhaps labeled as "Remux Only" or "Change Container Without Re-encoding". When selected, HandBrake would copy the existing video and audio streams into the selected container format, preserving the original encoding settings.

**Benefits:**
- Provides a quick and lossless way to change file formats to ensure compatibility with various devices and players.
- Reduces processing time and system resource usage since re-encoding is bypassed.
- Maintains the original quality of audio and video streams without any generation loss.

Thank you for considering this suggestion. I believe this feature would greatly enhance HandBrake's functionality and appeal to a wider user base.

**Comment by galad87** [comment]
Not planned at the moment. Anyway, this is the repository for the documentation.
