### ISSUE TITLE
handbrake.fr/docs results in Not Found

### ISSUE THREAD

**Issue by Rouneq** [HandBrake/HandBrake-docs#209]
Attempting to visit the online docs results in a "Not Found" page.

**Comment by bradleysepos** [comment]
```
HTTP/2 200 
server: nginx
date: Sat, 23 Dec 2023 21:23:09 GMT
content-type: text/html
content-length: 1063
last-modified: Fri, 22 Dec 2023 19:24:31 GMT
```

Seems to work here. Can you provide any additional information?

**Comment by Rouneq** [comment]
It's working again. It was just the docs and not the main site. No idea. Christmas gremlins?
