### ISSUE TITLE
Misidentification of Audio (number of audio channels)

### ISSUE THREAD

**Issue by 1pp1k10k4m1** [HandBrake/HandBrake-docs#21]
Issue:

On version 1.0.7 (build 2017040900), occasionally Handbrake will misidentify the number of audio channels on AC3 encoded audio. It only appears to happen on certain files. In this case, the audio is 5.1 channel (6 channel) AC3, and is being identified as 2.0 AC-3. I don't believe this can be classified as an error, or even a true "misidentification". It may just be a case of Handbrake being too good at its job, in which case this becomes a feature request to have Handbrake present the user with either option or alternative options. 

In MediaInfo, this appears as Channel(s): 6-channel vs Channel(s)_Original: 2-channel. I'm not a software developer and realize it can get tremendously complex, but I assume this means Handbrake scans whatever parameter MediaInfo is associating with Channel(s)_Original vs scanning Channel(s), or scanning both. MediaInfo report attached.

Conditions: 

This appears to happen when the "original" audio was 2-channel, and converted to 6-channel. Handbrake seems to detect the original audio configuration, instead of the "reworked" audio. 

Workaround: 

This is not a huge issue, as you can easily use MKV tools to extract and sync them to the newly encoded video (effectively replacing the audio from the old file into the new file), but it would be nice to see a fix if possible. 

Request:

If possible, it would be nice to see the ability to select either version in Handbrake if feasible and time permits. Thank you!

![screen shot 2017-07-03 at 10 41 40 am](https://user-images.githubusercontent.com/3910800/27797827-08ad0696-5fdd-11e7-9bf4-f6bbec57110e.png)

[Media_info_output_handbrake_issue.txt](https://github.com/HandBrake/HandBrake-docs/files/1119931/Media_info_output_handbrake_issue.txt)

**Comment by bradleysepos** [comment]
This issue tracker is for the HandBrake Documentation project. You can open a new issue for HandBrake here: https://github.com/HandBrake/HandBrake/issues
