### ISSUE TITLE
CQ NvEnc Encoding Goes No Higher Than 33Mbps

### ISSUE THREAD

**Issue by DigitalFoundryUK** [HandBrake/HandBrake-docs#211]
Hi

I use Handbrake's NvEnc h265 encoding to archive 4K 59.94fps video using CQ encoding, typically at CQ 18 for 4K and CQ 14 for 1080p.

What I'm finding is that most recent revisions of Handbrake don't scale bitrate to the required quality level. I can only get circa 26-33Mbps encodes which are of poor quality. This applies to the new AV1 encoding too.

I have to go all the way back to Handbrake 1.2.2 for CQ encoding to work properly with NvEnc (it's not an Nvidia driver issue) whereupon I get the circa 100-200Mbps I would expect from CQ 18 4K encodes. Any revision of Handbrake newer than this breaks the CQ encoding. 

Would be great if this can be fixed as I'd love to use the new AV1 functionality.

Thanks!

**Comment by galad87** [comment]
This is the documentation issue tracker, there is a similar issue open on https://github.com/HandBrake/HandBrake/issues/2873
