### ISSUE TITLE
Help or features to convert 3D SBS and HOU movies 

### ISSUE THREAD

**Issue by knopserl** [HandBrake/HandBrake-docs#214]
It would be very helpful if 3D SBS/HOU videos could be converted.
I read some of the only few availabe hints how to do, but it seem to require a couple of steps.
Not sure if Handbrake can do that out of the box with some predefined profiles or if this would require some code enhancements or ...

**Comment by sr55** [comment]
3D is not supported in HandBrake.

Also, please be aware this is the documentation repository.  For any feature requests please goto https://github.com/HandBrake/HandBrake
