### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by sldprt** [HandBrake/HandBrake-docs#22]
I am not sure why I cannot pick drive, or folder, and the software wont go deeper into directory levels? I am willing to help contribute this functionality if guided a little. This seems like very simple functionality yet totally over looked. I may be missing something so I would appreciate some feed back on the topic.

I would also like the ability to keep folder structure even when moving files to the trans coded directory.

Thanks,

**Comment by bradleysepos** [comment]
This issue tracker is for the HandBrake Documentation project. You can open a new HandBrake issue here: https://github.com/HandBrake/HandBrake/issues
