### ISSUE TITLE
Inquiry: Offline .html build of handbrake documentation

### ISSUE THREAD

**Issue by doe34149** [HandBrake/HandBrake-docs#225]
i was wondering if there were any plans to take the existing documentation you have online and package it into an offline installer, such as the gimp project has done, to make the help files accessible without an active internet connection.

examples:

https://docs.gimp.org/download.html

![gimp_help_browser_local](https://github.com/HandBrake/HandBrake-docs/assets/175041256/96385243-9ccc-457d-989c-e5f597df39a1)

**Comment by doe34149** [comment]
thank you for the work you do. it is people like you who make high quality, free and open source software who make the usage of a pc an open and financially accessible experience. i am very grateful for you, and the creators of software such as GIMP, OpenOffice, Audacity, fre:ac, kdenlive, VLC, and an innumerable list of others. you guys are really cool, and i just wished to use this opportunity to ensure you knew that. again, thank you for all you do.

**Comment by sr55** [comment]
The documentation is available for download in HTML format (See the releases section).  It's just HTML, JS and CSS so no web server needed. It can be viewed in any browser. 

I've updated the releases description to provide more detail on usage.
