### ISSUE TITLE
AV1 10 bit HDR10+ Metadata Dropped

### ISSUE THREAD

**Issue by wex1248** [HandBrake/HandBrake-docs#226]
Tried many files with HEVC 10 bit HDR10+ to AV1 10 bit. In all cases, HDR10+ metadata is dropped.
Dolby Vision sees to work perfectly, but I have a Samsung S95C that ignores DV.   The documentation says it AV1 10 bit HDR10+ works!?!

**Comment by sr55** [comment]
This is the documentation repository.  Please use https://github.com/HandBrake/HandBrake  to raise any "Issues" or Questions via "Discussions".
