### ISSUE TITLE
Audio Codec issue with DTS-HD MA

### ISSUE THREAD

**Issue by BrianS69** [HandBrake/HandBrake-docs#227]
My source is DTS-HD MA 5.1
I'm trying to use DTS Passthru but it's not available after updating to Handbrake version 1.8.2
In the past I've always used Auto Passthru for my audio codec to match my source but it's missing, with DTS as the source.
My other 2 audio sources are AC3 and AC3 Passthru is available for those.
![image](https://github.com/user-attachments/assets/0a67045a-58da-429b-8a59-33088721e56c)

**Comment by sr55** [comment]
This is the documentation repository.  Please use https://github.com/HandBrake/HandBrake  to raise any "Issues" or Questions via "Discussions".
