### ISSUE TITLE
file: opening multiple video file(s) only opens one file, the first file

### ISSUE THREAD

**Issue by goofyseeker311** [HandBrake/HandBrake-docs#228]
I was supposing that it would automatically queue every file using the current selected profile.
but it only started processing one file, the first one. no I specifically tested how and wanted the
normal file open to open multiple files, not the queue files functionality, which is also there.
I have not tried to the other functionality, and will not if the normal open file can handle multiple files.

optimal functionality with the file: open video files(s) with multiple files is that it would list the files
and process all of them when pressing start encode. not even directory batch, but multiple selected individual files.

**Comment by sr55** [comment]
This is the documentation repository.  Please use https://github.com/HandBrake/HandBrake  to raise any "Issues" or Questions via "Discussions". 

>I was supposing that it would automatically queue every file using the current selected profile.

Nope,  You have to add the titles you want to the queue first.  Either invidiously or using the batch "Add Selection" and "Add All" options. 

The workflow is designed to operate as follows:   Load Source -> Configure Settings -> Add to Queue -> Start.

**Comment by goofyseeker311** [comment]
imho the program should add all the opened files into the queue.

**Comment by sr55** [comment]
That's not how HandBrake is designed to work.   There are many different use-cases that HandBrake supports and that particular behaviour you are requesting would break a number of them.  We cannot blindly assume user intent.  That would cause a lot of users to have a bad experience.  I.e Where users have batches of files with different settings for each job.

**Comment by goofyseeker311** [comment]
maybe, but it breaks the first time user experience. your choice.
