### ISSUE TITLE
Lack of glossary and/or search in docs (what is "RF"?). 

### ISSUE THREAD

**Issue by jtheletter** [HandBrake/HandBrake-docs#24]
There seems to be no native means to search the documentation, nor any glossary of terms. 

https://handbrake.fr/docs/en/1.0.0/

At present, this would help me understand what "RF" (commonly used throughout docs) means. 

Thank you.

**Comment by bradleysepos** [comment]
Yes, a glossary of terms will be helpful once we add one. CRF (or simply RF) means Constant Rate Factor. It's the metric used for quality based encoding. See the Adjusting Quality article.

**Comment by bradleysepos** [comment]
Add this to the end of your Google Search terms to search the docs specifically: site:handbrake.fr/docs

**Comment by jaepage** [comment]
I did a Google site search as well as a Google web search. Did not find an obvious definition. Thank you.

**Comment by bradleysepos** [comment]
It's been awhile, obviously, but I did eventually get to addressing this following some other documentation updates. The new wording should clarify Constant Rate Factor/CRF/RF and will be live shortly. Thanks for the heads up. 😸
