### ISSUE TITLE
How to convert/add subtitle to video without altering any settings?

### ISSUE THREAD

**Issue by maivutan** [HandBrake/HandBrake-docs#25]
I just want to convert a video to .mp4 or add subtitle to it, while maintaining quality and all settings untouched. How can I do this? I don't want to touch the preset... because I don't know which is best and I don't know current video's quality so I'm afraid the presets will scale down its quality.

Or is it I just need to select the preset with highest quality and everything will remain untouched?

**Comment by bradleysepos** [comment]
This is the issue tracker for HandBrake Documentation. You're probably looking for the issue tracker at https://github.com/HandBrake/HandBrake/issues

In short, HandBrake always converts video. It sounds like you're looking for a muxer like Subler or MKVToolNix.
