### ISSUE TITLE
documentation Centos 6 dependencies broken link ?

### ISSUE THREAD

**Issue by bman765** [HandBrake/HandBrake-docs#26]
Hi, 

Using the documentation at https://handbrake.fr/docs/en/latest/developer/install-dependencies-centos.html for CENTOS 6, I noticed the download URL for the .spec file is broken : 
curl -o /root/rpmbuild/SPECS/harfbuzz.spec 'https://git.centos.org/raw/rpms!harfbuzz.git/f5bd1f4920ed0fc56cd21547294f7c34deeb4e4f/SPECS!harfbuzz.spec'

Is this a problem that exists from my end or can this be fixed please ? 

Tx for any reply

**Comment by bradleysepos** [comment]
Thanks for the report, I’ll look into it. Would be a shame if CentOS overwrote something in their repository like that, but it could just be they changed their web interface.

**Comment by bradleysepos** [comment]
Looks like they did something to change the commit hash, everything else appears the same. Try this link:

https://git.centos.org/raw/rpms/harfbuzz.git/4f97df9e63e0f3143280d918b3f55ddeae513551/SPECS!harfbuzz.spec

Please report back if all goes well and I’ll get the docs updated soon, thanks.

**Comment by bradleysepos** [comment]
Fixed in a0e325649bd72b57027d972ff7c08de3872f3e30. Will go live whenever @sr55 has time.

**Comment by sr55** [comment]
Refreshed.
