### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by vr8hub** [HandBrake/HandBrake-docs#28]
From the last sentence in the Project History section:
> Today, HandBrake is will hosted by titer the the development team remains in contact however he is not active in the day to day running or development of the project.

I'm pretty certain the "will" and double "the" in the above are mistakes, and the italicized words below were my best guesses as to what they should be (they shouldn't be italicized in the docs, obviously). For the additional punctuation, i.e. the semi-colon and comma, the former is debatable, but some kind of break is needed there (could be a period with the "However" starting a new sentence).

> Today, HandBrake is _still_ hosted by titer _and_ the development team remains in contact; however, he is not active in the day to day running or development of the project.

**Comment by bradleysepos** [comment]
Fixed, thanks!

**Comment by bradleysepos** [comment]
Aside, another developer is pushing the documentation to the site manually for security reasons, so it may take a bit for the changes live.
