### ISSUE TITLE
Building for Windows Documentation

### ISSUE THREAD

**Issue by ajkajk** [HandBrake/HandBrake-docs#30]
I've been switching from using a VM to using the new Ubuntu app built on Windows Subsystem for Linux. This runs Ubuntu 16.04.3 LTS.

Following the current documentation at https://handbrake.fr/docs/en/latest/developer/build-windows.html revealed a couple of errors and perhaps deficiencies.

### Problems with Dependencies

*    Using a fresh installation, the quoted dependencies can't be installed without first issuing a `sudo apt-get update` command - otherwise `yasm `is not visible. It would be good practice to bring the installed system up-to-date at the same time i.e. `sudo apt-get upgrade && sudo apt autoremove` after the `update`.

      I think these commands should be included in the documentation

*    The actual list of dependencies doesn't include those needed to run the `mingw-w64-build` script. Further packages needed, of those listed in the script as requirements, are `bison bzip2 flex g++ gunzip pax`.

*    Although `libtool `is listed as a dependency, it is not recognised by the configure script unless `libtool-bin` is also installed. Although the script has facilities for building this (and `pkg-config`) if missing, this didn't work for me.

The sufficient dependencies to add to a fresh install that I found were `bison cmake curl flex g++ gcc git intltool libtool libtool-bin m4 make patch pax pkg-config python tar wget yasm`.  (Some of these e.g. `git` are in fact installed in the released system.)

I think the list in the documentation should be updated. (The list for building for Ubuntu at https://handbrake.fr/docs/en/latest/developer/install-dependencies-ubuntu.html provides another view - it doesn't include `pax` for example.)

I imagine these results would be the same in a fresh native install of Ubuntu.
### Controlling the build

The documentation gives no guidance on controlling the build.

* For users wishing to build a release version of HandBrake for example to include the fdk-aac encoder, I think a mention of the use of the git tag facility as used by HandBrake should be included i.e.
```
    git tag (this lists the tags)
    git checkout tags/1.0.3 (or whichever version you want from the list),
```
      This allows the specific version of HandBrake to be built.

* Similarly, the options available with configure aren't mentioned. The facility to list usage by calling `./configure -h` might be included. In any case the specific case of building to include the fdk-aac encoder, i.e. the `--enable-fdk-aac` option, could be explicitly mentioned given that is probably a motivation for building your own

### Using Windows Filestore

If the option of using the Windows Ubuntu app is documented, the following might also be noted.

MS recommend using Windows filestore (DrvFs) for this sort of work i.e. placing the source somewhere in the regular Windows user NTFS space and linking to this from the Linux world, rather than cloning HandBrake to `~/HandBrake`. This has the advantage of being able to build the GUI from the same clone as the dll, rather than maintaining two workspaces. (That was a reason for me to do this anyway.)

There are a couple of problems with this currently.

*    When using GNU tar to extract source, the original file times of the source files are not maintained. This plays havoc with subsequent attempts to make. I've raised a bug report with MS and they will eventually fix this. In the meantime, you can use the port of bsdtar from http://gnuwin32.sourceforge.net/packages/libarchive.htm by quoting the path e.g. `--gtar=/mnt/c/SW/GnuWin32/GnuWin32/bin/bsdtar.exe` to `configure`.

*    Also, there is some problem with using concurrency. The build works if make is not asked to run more than 1 job at a time i.e. `--launch-jobs=1` or a call of make without any options works. I've not tried to diagnose this - it may be a fault in the build system exposed by the different scheduling running against the Windows Linux kernel implementation.

Whether either of these issues ought to be documented in the HandBrake build for Windows documentation I don't know.

I've only used a toolchain built-in Linux filestore (VolFs) i.e. `scripts/mingw-w64-build x86_64 ~/hbtoolchain`
### Building using MSYS2

For building for Windows, an alternative to build from a single workspace is to use gcc from the MSYS2 environment. This isn't currently documented for Handbrake and since the build system supports it, perhaps this ought to be documented here too.

After installing MSYS2 from http://www.msys2.org/ and updating with

```
pacman -Syu
pacman -Su
```

I added the following packages:

```
pacman -S base-devel cmake diffutils gcc git make mingw-w64-cross mingw-w64-cross-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-yasm yasm
```

And then ran

```
git clone https://github.com/HandBrake/HandBrake.git && cd HandBrake
./configure --cross=x86_64-w64-mingw32 --enable-qsv --enable-fdk-aac --launch-jobs=10 --launch

```
This is all in an MSYS shell rather than a MINGW64 shell - the latter fails in configure unable to find `x86_64-w64-mingw32-ar`

**Comment by bradleysepos** [comment]
Thanks @ajkajk for moving the issue to this repo. Updates as follows.

Package updating: `apt-get/yum update` added where relevant. https://github.com/HandBrake/HandBrake-docs/commit/8e79c56e02294f6591f4689cf675f846d435c86d

I'm not sure this is the proper place to educate people about upgrading and autoremoving packages. Best practice, but not really HandBrake's domain. We have to draw a line somewhere, and given the already high number of people who ask for help with HandBrake but really need help with Linux administration, I think the line belongs here. I really don't want to spend time debugging the output of upgrade/autoremove, and I can guarantee that's what would happen. Hopefully this is understandable. 😸

`mingw-w64-build`: Added dependencies list and install commands where relevant. Very useful, thanks for the tip. https://github.com/HandBrake/HandBrake-docs/commit/3e2d7b9a50005ac55ce9c4ded81ebb8c64b5e40c

`libtool-bin`: Already listed as a dependency for 16.04+. Let me know if you see any error/typo regarding this.

Release tags: Updated release docs (e.g., 1.0.x) to list related tags and then check out the most recent. We don't want to list all tags as most are old and irrelevant, so this keeps things contextual. https://github.com/HandBrake/HandBrake-docs/commit/6edf6f659ae58599cef5fc55e5fca711d485f8ac

Build system usage: Our old documentation had a section on build system commands that I have archived and hope to integrate again soon. Tracking on #32. In the meantime, Scott and I have added information about `--enable-fdk-aac` to the latest docs.

MSYS2: Thanks to @maximd33 MSYS2 building has recently become possible on master branch. I am hoping to add documentation soon, but will need some guidance. I should probably get a VM going for this. Tracking on #31.

Windows Filestore: @sr55 do you have any comments on this?

**Comment by sr55** [comment]
I occasionally use The Linux Subsystem but I'd typically recommend that people not use it. IO Performance there is atrocious so builds take a really long time even on high end hardware. I typically run SFTP via WinSCP to edit files. Works reasonally well since you can't touch the filesystem files without the sub system failing badly.

**Comment by ajkajk** [comment]
* I mislead you about the `mingw-w64-build` script.  The dependencies it checks for are the names of the programs it runs.  In the case of gunzip, the package that delivers this is gzip.  So the full list of _package_ dependencies the script specifies is `bison bzip2 curl flex g++ gcc gzip m4 make pax yasm`, the extra ones being `bison bzip2 flex g++ gzip pax`. Sorry.

* `libtool-bin` isn't mentioned in the _Windows_ build dependencies, which assumes Ubuntu 16.04 LTS. (It is mentioned in the Linux instructions for Ubuntu 16.04 but you wouldn't expect a Windows user to look there.)  Without it, you, or perhaps just I, can't build.   

* As I said, I also can't complete the build without also including `pkg-config`.  So I still think you need to include that.  

* By the way, one other thing I find is, if you are using Windows filestore (WSL or MSYS2), Windows Defender really goes to town on the files generated when building - I find it pays to make a suitable exclusion to avoid this - I don't know about other virus checkers

**Comment by maximd33** [comment]
dont have much complains about Defender etc

I have VM support turned off, even on BIOS - just not a big fan, therefore MSYS2

> MSYS shell rather than a MINGW64 shell 

good observation, I believe is already stated.

**Comment by ajkajk** [comment]
A full build of HandBrake (not the toolchain) using WSL VolFs on my 5-year old i5 2.5GHz laptop takes a little under 25 mins.  It's improved with the latest (Fall Creators Update) release.  I think MSYS2 is comparable.  I can't remember the VMWare time, but it wasn't lightening fast.

Since the WSL DrvFs seems to have problems, I think I'm going to use MSYS2, so that I can straightforwardly integrate with Visual Studio.  

I am right that the mingw-w64-build script doesn't run there. Clearly the MSYS2 compiler version is potentially different from the one the script mandates, but not broken.

**Comment by sr55** [comment]
Yeh, that older CPU probably isn't as Disk bound as some newer ones.

The difference for me is ~30 minutes to 2 minutes 4s.  It's all IO and I didn't notice any improvement with FCU.  It was actually quicker until john added 2 more x265 compiles for 10/12bit :(

**Comment by bradleysepos** [comment]
> I mislead you about the `mingw-w64-build` script.

Ha, no worries. I wrote the `mingw-w64 build` script! And I know `gunzip` is part of `gzip`! And I still got it wrong! Fixed. 😸

> `libtool-bin` isn't mentioned in the *Windows* build dependencies

Ouch, you're right. Probably got missed when updating from 14.04. Fixed.

> As I said, I also can't complete the build without also including `pkg-config`. So I still think you need to include that.

Done.
