### ISSUE TITLE
program wont remember subtitles defaults

### ISSUE THREAD

**Issue by davidhold** [HandBrake/HandBrake-docs#34]
every time i start a session after i load a video subtitles are always turned on and forced burn in....
i click reload defaults and it has always changes to on .... burn in... i have to before a session always configure the defaults to subtitles off and reload defaults.... when i quit the program and launch again subtitles are back on, burn in

**Comment by bradleysepos** [comment]
@davidhold Sorry you're having trouble. What you want to do is select "Configure Defaults" in 1.0.7 or "Selection Behavior" in the nightly build, on the subtitles tab, and configure your settings there. Then save a new preset and use that.

If you're still having problems, please open a new issue on the HandBrake tracker (this is for the documentation project): https://github.com/HandBrake/HandBrake/issues
