### ISSUE TITLE
How to Apply Some X264 Parameter in Advanced Option String?

### ISSUE THREAD

**Issue by Gosokan** [HandBrake/HandBrake-docs#36]
I know some parameter name and value in mediainfo must adjusted to comply with handbrake option string. Such as:

keyint_min=30 become mint-keyint=30 in handbrake
deblock=1:1:2 become deblock=1,1|2
psy_rd=1.00:1.00 become psy-rd=1|1

But, how apply this parameter in handbrake advanced option string?
chroma_qp_offset=-2
cplxblur=20.0
qblur=0.5

Because after encoding finished and I check video files result using mediainfo, these parameter become:
chroma_qp_offset=-6
cplxblur and qblur is not defined (not mentioned) in mediainfo

Thank you for help

**Comment by bradleysepos** [comment]
keyint-min=30:deblock=1,1,2:psy-rd=1.00,1.00:chroma-qp-offset=-2:cplxblur=20.0:qblur=0.5

It is possible that MediaInfo is simply not aware of cplxblur and qblur.

In the future, please request support on [HandBrake's issue tracker](https://github.com/HandBrake/HandBrake/issues) (this one is for the documentation project). :smile_cat:
