### ISSUE TITLE
GUI allows for Invalid TrueHD Audio Passthru and MP4 Container Selection

### ISSUE THREAD

**Issue by samualblair** [HandBrake/HandBrake-docs#38]
I was excited to see HandBrake add support for TrueHD recently (thanks!).
Unfortunately I had a couple failed transcodings in which I selected TrueHD 7.1 using and MP4 in which I was left with no Audio or mixdown AC3 5.1. I was thinking this was a buggy new feature, but after some digging did I find that TrueHD is only supported with MKV container.

It seems the GUI allows for Invalid TrueHD Audio Passthru and MP4 Container Selection.

It would be great the handbrake GUI prevented selection of TrueHD Passthru while using the MP4 container, or at least throw a warning about it.

**Comment by sr55** [comment]
This is something that was already fixed some time ago and will be in the upcoming 1.1 release.

p.s This is the documentation issue tracker, not HandBrake issue tracker :)  See https://github.com/HandBrake/HandBrake/issues  for the app issue tracker.

Thanks

**Comment by samualblair** [comment]
Glad to hear, and sorry about posting in the wrong section. Thank you for the link!
