### ISSUE TITLE
Add support for #operating_system

### ISSUE THREAD

**Issue by sr55** [HandBrake/HandBrake-docs#40]
Adding support for #operating_system to automatically select a defined OS when providing links on forums etc.

**Comment by bradleysepos** [comment]
Implemented by f9bff56f47ec48f6d7c889a4b841ada93e0c063b, 5493c9db0e75e044f42c2a483a7e3d7ec8e8086d, and 313d38054466bd0e75834688a97e10458a3d25a7.
