### ISSUE TITLE
v1.1.0 - 64bit - Subtitles are a total mess over here

### ISSUE THREAD

**Issue by OldRisc** [HandBrake/HandBrake-docs#42]
**Hi, I created a preset and the subtitles behavior selection looks like this**

![a1](https://user-images.githubusercontent.com/35472884/39369431-8e34d2cc-4a3c-11e8-9f74-cc15494f721a.jpg)

**what gives me this**

![75bd9552-0cf4-4ec7-8e4a-e281d203e78f](https://user-images.githubusercontent.com/35472884/39369557-ed468f08-4a3c-11e8-9078-bbeb95af1f0c.jpg)

**which is wrong regarding** _Burn in_. **For whatever reason** _Brun in_ **is also protected and can't be deselected. If I chose** _Default_ **then** _Burn in_ **goes away. Odd behavior.**

![d93b7519-a915-45e0-bcc5-23d67333061d](https://user-images.githubusercontent.com/35472884/39369715-51e005b6-4a3d-11e8-930e-86683cfce9f8.jpg)

**So I changed the preset to this**

![a3](https://user-images.githubusercontent.com/35472884/39369744-69c25c92-4a3d-11e8-8521-cd5906866cba.jpg)

**and got this**

![a4](https://user-images.githubusercontent.com/35472884/39369755-71ae2ae4-4a3d-11e8-93a6-21217f37a282.jpg)

**so I decided to delete the last one resulting in this**

![a5](https://user-images.githubusercontent.com/35472884/39369791-8178b11a-4a3d-11e8-9c2d-13bd9e10fb9b.jpg)

**But the result in the end in e.g. VLC is this**

![a6](https://user-images.githubusercontent.com/35472884/39369824-937c1686-4a3d-11e8-8975-a65d22aa501c.jpg)

**and the german subtitle is burned in again.**

**What the heck is going on?**

**Thx!**

**Comment by bradleysepos** [comment]
Sorry you're having trouble. Please repost this over at the [HandBrake issue tracker](https://github.com/HandBrake/HandBrake/issues) (this tracker is for documentation).
