### ISSUE TITLE
Add Performance article including decoding speed information.

### ISSUE THREAD

**Issue by Martin-Pitt** [HandBrake/HandBrake-docs#43]
I'd like an article on video decoding speed/performance to sit alongside the encoding one.
Even if it's just a stub article with a few bullet points to keep in mind.

----

One of the issues I face is that I often try to balance out video decoding performance when creating web apps, whether as a PWA, Cordova or in Electron.

Particularly as I tend to work on Electron apps for conferences that tend to be interactive and sometimes we want to add videos.

I have built a rough understanding of video decoding performance, but to be honest, I still feel like I am blindly stumbling through the settings in Handbrake.

I'm not the only one that wonders about decode performance it seems either. I often try to share what little I know, sometimes even having to advise designers on such a complex topic.

It's vaguely mentioned in the encoding article, but I think an page aimed at decoding performance specifically would immensely useful and show up during google search results.

**Comment by bradleysepos** [comment]
Thanks for the suggestion. I do think a performance article would be helpful, and we can add small snippets with links to it on other articles as necessary. Will add it to my list.

Specifically to decoding, it seems you are looking for information about optimizing for low power, fast decoding for apps and the web. Basic advice for x264 is to use a fast encoder preset to avoid complex options and a reasonable RF/quality. You may also want to use baseline or main profile (especially where hardware decoding is not available) and the lowest level supporting your resolution. https://en.m.wikipedia.org/wiki/H.264/MPEG-4_AVC#Levels

**Comment by bradleysepos** [comment]
I should add, given enough time I may create some web video presets for HandBrake 1.2.0. What codecs, resolutions, and quality are you typically targeting?

**Comment by bradleysepos** [comment]
Added in https://github.com/HandBrake/HandBrake-docs/commit/39d48999fd72b28a10b98633731b749099d02774, see https://handbrake.fr/docs/en/latest/technical/performance.html
