### ISSUE TITLE
Document new speex, lzma dependencies

### ISSUE THREAD

**Issue by frederickding** [HandBrake/HandBrake-docs#44]
As a result of the ffmpeg switch, speex and lzma are now build dependencies. (See HandBrake/HandBrake@4f2a33e550e941ffebebe0697cd362a977fdc2f6 , HandBrake/HandBrake@af5cb50275cea1a17a934aa71df2ecdd3aee9657, HandBrake/HandBrake@3c1eca4ee7630e04674c3b5443627241ef56f106 .)

These new requirements led to failed builds from master, despite following the old instructions. Once the new build dependencies are all known, please consider adding them to the docs (e.g. at https://handbrake.fr/docs/en/latest/developer/install-dependencies-ubuntu.html).

**Comment by bradleysepos** [comment]
I'm literally in the middle of this. 😸 Sharp minds think alike.

**Comment by frederickding** [comment]
For Fedora, it appears the new packages are

- speex-devel
- xz-devel

**Comment by jstebbins** [comment]
And ubuntu is
- libspeex-dev
- liblzma-dev

**Comment by bradleysepos** [comment]
These are updated and will be automatically published tomorrow. Still working on other distros.

**Comment by bradleysepos** [comment]
Everything should be up to date with the exception of Gentoo, which will take some time and head banging because I have a lot of updating to do.

**Comment by bradleysepos** [comment]
Dependencies for all distros are up to date and tested. 😸 

If anyone notices anything missing or broken, feel free to open a new issue.
