### ISSUE TITLE
Just a couple typos in the documentation

### ISSUE THREAD

**Issue by rmlrml** [HandBrake/HandBrake-docs#55]
Hello.  Sorry if you don't like typos being posted here.  I was unsuccessful connecting to irc freenode #handbrake.

Just a couple typos I just came across in [Docs > English > HandBrake 1.1.0 > Video Encoding Speed](https://handbrake.fr/docs/en/1.1.0/technical/video-encoding-performance.html), in the "Source" paragraph at the bottom:

"For example the H.254 decoder..." instead of H.264, and
"...are simpler, this, you have..." looks like it should be "thus" instead of "this".

Peace!

**Comment by bradleysepos** [comment]
This is a great place to report typos, thanks. 😄

That article is a carryover from the old wiki we used to have and needs completely rewritten. In the meantime, I'll get those changes made when I have some time again soon. Thanks again.
