### ISSUE TITLE
Add gstreamer1.0-libav to Ubuntu 18.04 (Bionic) dependencies.

### ISSUE THREAD

**Issue by bradleysepos** [HandBrake/HandBrake-docs#65]
So I don't forget.

**Comment by jstebbins** [comment]
It's not really a dependency in the classic sense.  

I.e. it's not required in order for the build to succeed.  It is a runtime dependency in order to decode certain codecs.  But other gstreamer plugins can also be used to satisfy those runtime dependencies.  I.e.  there is a ffmpeg plugin does the same thing as libav plugin and a fluendo plugin that satisfies many if not all of the necessary codec dependencies.

**Comment by bradleysepos** [comment]
Indeed, it's a runtime dependency and I was going to note it as such, if that works for you @jstebbins. I didn't have luck with the ffmpeg 0.10 one, for whatever reason.

My main concern is that it's a bit jarring to encounter a decoder error (usually two at once). The average user will likely just blame the application, and I've seen various reports around the web to that effect. So I think we should at least document how to proceed so it works out of the box for regular folks. If someone more knowledgeable wants to use a different plugin package, that's fine, too. I guess the real question is whether we mention the alternatives.

**Comment by jstebbins** [comment]
Giving one example that works in most cases and saying that there may be alternatives available depending on your distribution should be good.

**Comment by bradleysepos** [comment]
After further investigation, it seems that only `gstreamer1.0-libav` is listed by Ubuntu's package search for Bionic: https://packages.ubuntu.com/search?keywords=gstreamer&searchon=names&suite=bionic&section=all

The only package coming up for fluendo is an mp3 codec, and the ffmpeg plugin doesn't seem to be listed at all now.

It seems effective enough to list `gstreamer1.0-libav` as a graphical interface dependency. While it wasn't my original intention, it does seem fair enough given live preview won't work with most official presets without it, and other options seem slim on the specific platform.

See #66.
