### ISSUE TITLE
Links to community forums is incorrent and broken.

### ISSUE THREAD

**Issue by Numbergod** [HandBrake/HandBrake-docs#69]
https://github.com/HandBrake/HandBrake-docs/blob/master/CONTRIBUTING.markdown

All the links to the community forums on the above page need updating to 

https://forum.handbrake.fr/

I can't see how to do it easily.

Also.  Where did the Clear Queue go?  I really liked that.

**Comment by bradleysepos** [comment]
Fixed. Thanks for pointing this out.

Clear Queue on Windows is accessible via the right-click/context menu.
