### ISSUE TITLE
GUI to CLI JSON no longer supported?

### ISSUE THREAD

**Issue by inspector71** [HandBrake/HandBrake-docs#76]
Thanks for this great software.

The documentation here:

https://handbrake.fr/docs/en/latest/cli/command-line-reference.html

... refers to:

` --preset-import-file <filespec>
                           Import presets from a json preset file.
                           'filespec' may be a list of files separated
                           by spaces, or it may use shell wildcards.`

However the binary I just installed via ...

`add-apt-repository ppa:stebbins/handbrake-releases`

.. has no such option.

Yet, the GUI program only allows exporting settings to a `.json` file and the previous versions had a section where the command line options were visible in a text field.

I seem to remember previous versions had a hidden easter-egg like mode to reveal more preset definitions although may be mistaken.

Is there a currently-supported means to take GUI-customized presets and apply them via CLI?

**Comment by bradleysepos** [comment]
What distro and version are you using? `--preset-import-file` hasn't gone away, afaik.

**Comment by inspector71** [comment]
I was using Debian 9.

**Comment by jstebbins** [comment]
Can you post an activity log of HandBrake starting up so we can see all the version information etc.  It sounds like you've installed either a very old version or some other version that was not built by us.

**Comment by jstebbins** [comment]
> Yet, the GUI program only allows exporting settings to a .json file and the previous versions had a section where the command line options were visible in a text field.

Only the windows version ever had an option to show the CLI command. Neither the linux or OSX versions ever had this.  Many years ago, the windows version used the cli under the covers.  Now it interacts with the core library directly, so it no longer has the option to show the cli command.

> Is there a currently-supported means to take GUI-customized presets and apply them via CLI?

The supported way is to export the preset as json and read it with the CLI using --preset-import-file.  There is also a way to export the queue and have the CLI run the queue with --queue-import-file.

**Comment by jstebbins** [comment]
And you posted to the wrong project.  This is the documentation project.  Issues with the application should go here https://github.com/HandBrake/HandBrake/issues.

**Comment by inspector71** [comment]
I thought the documentation was incorrect or did not reflect the current
scenario.

I thought there was a mismatch.

So I posted in the correct project, actually.
