### ISSUE TITLE
Select preview image

### ISSUE THREAD

**Issue by akselsoft** [HandBrake/HandBrake-docs#80]
I may have missed this but didn't see this feature mentioned.

When a video is first loaded for conversion, it creates a preview that will be used as the icon content for the generated video. You can change the preview image by clicking the arrows at the bottom of the preview window.

This is really useful if the content includes possible spoilers or better titles. (I was about to create a feature request on this when I discovered it)
<img width="770" alt="Screen Shot 2019-06-17 at 4 35 01 AM" src="https://user-images.githubusercontent.com/642423/59590129-5de2b980-90b9-11e9-9e35-2b6fbd62eebf.png">

**Comment by galad87** [comment]
No, those preview images will not be used as the icon content.

Anyway, this is the HandBrake-docs issue trackers, if you have an issue with HandBrake, use the HandBrake issues tracker.
