### ISSUE TITLE
rotate not working in V1.1.2

### ISSUE THREAD

**Issue by CodeKraft** [HandBrake/HandBrake-docs#83]
Just downloaded a video that is mirrored.

As this version insists it is the most current, there is no rotate and flip and other options as stated in the documentation, I tried the --rotate=2; in the more options under video and it produced the same stream as what I already has and actually made the file bigger not smaller.

When is handbrake going to do exactly as it states on the tin?

**Comment by bradleysepos** [comment]
Perhaps when you update to the latest supported version, which is 1.2.2. Otherwise, please open an issue on the HandBrake issue tracker and provide an activity log. This is the documentation tracker.
