### ISSUE TITLE
Documentation for updating on Windows is outdated.

### ISSUE THREAD

**Issue by mrmsbarnes** [HandBrake/HandBrake-docs#84]
Now we go to About Handbrake > Updates > Check for Updates

**Comment by bradleysepos** [comment]
We reviewed https://handbrake.fr/docs/en/latest/get-handbrake/check-for-updates.html and the instructions appear to be correct. If there is still an issue, please be more specific about where the problem lies in the documentation. Thanks.

**Comment by bradleysepos** [comment]
https://github.com/HandBrake/HandBrake/commit/2dff6f93940c1d1d16b04d2b33c3b21ba910a186 improves the behavior for the About menu item, automatically performing the update check.

**Comment by mrmsbarnes** [comment]
In those situations where you want to know for sure that any possible update is made before you start your work, it’s important the user can choose so.  Automatic means you have some Windows startup task constantly looking for updates or listening for heaven knows what push.  I have too many of these “helpers”.

 

When I click Help on Handbrake version 1.2.2, I am thrown to this page:  https://handbrake.fr/docs/ - no mention of updates.

When I click on Preferences or About HandBrake, then I see an option for Updates.

For the documentation at https://handbrake.fr/docs/en/1.2.0/get-handbrake/check-for-updates.html, at

Updating HandBrake on Windows

there is this:

Manually checking for updates is easy. From the Help menu, select Check for Updates.... If an update is available, HandBrake will offer to install it for you.

which is what I was complaining about.  The first Help link just starts your browser on the page I mentioned.  We could argue about “link” and “menu”.  I didn’t see these terms defined in the docs.

 

But don’t worry.  I won’t bother you again.  I’ve found a better free editor to do what I want and its updating is straight forward.
