### ISSUE TITLE
Use mkfifo with handbrakeCLI

### ISSUE THREAD

**Issue by TBoyd9** [HandBrake/HandBrake-docs#85]
Actually I guess the question should be one for Screenflow - I want to pipe the Screenflow output into Handbrake.  Does anyone know how to do that?  Thanks.  Boyd

**Comment by galad87** [comment]
This is the HandBrake-docs repository, if you have an issue with HandBrake make a new issue in the right repository ;)

**Comment by bradleysepos** [comment]
Indeed, this is the documentation issue tracker (HandBrake-docs), not the project issue tracker (HandBrake).

A quick answer to your question is HandBrake only supports reading from complete files and is not compatible with piping / frame serving.

**Comment by TBoyd9** [comment]
Thanks.  That makes sense.
