### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by cholasimmons** [HandBrake/HandBrake-docs#95]
I would love the output directory to (by default) set itself to where I drag the source video from, or at least memorize the last location I exported to.
I use Handbrake everyday and it's cumbersome to always have to navigate to where I want the output to be

**Comment by SimonEast** [comment]
Hi @cholasimmons - this repository is for the Handbrake documentation. It sounds like you're submitting a feature/change request for the Handbrake application itself. For that, you'll probably need to post in a different forum at https://github.com/HandBrake/HandBrake/issues

Hope that helps?
