### ISSUE TITLE
Debian 9 nasm package link

### ISSUE THREAD

**Issue by slashinfty** [HandBrake/HandBrake-docs#99]
While building on Debian Stretch, the [instructions](https://handbrake.fr/docs/en/latest/developer/install-dependencies-debian.html) for `nasm` did not work as intended:
```
sudo curl -L 'http://ftp.debian.org/debian/pool/main/n/nasm/nasm_2.13.03-1_amd64.deb' -o /var/cache/apt/archives/nasm_2.13.03-1_amd64.deb
sudo dpkg -i /var/cache/apt/archives/nasm_2.13.03-1_amd64.deb
```
I received an error that the file was not a Debian format archive. However, I found a link [here](https://packages.debian.org/buster/amd64/nasm/download) for `nasm_2.14-1_amd64.deb` to be useful and lead to successful build.

**Comment by bradleysepos** [comment]
Indeed, it looks like Buster and unstable were using nasm 2.13.xx which was replaced with nasm 2.14.xx, after which the former debs were removed. That certainly doesn't make for stable documentation URLs. 😿

I tested `http://ftp.debian.org/debian/pool/main/n/nasm/nasm_2.14.02-1_amd64.deb` on Stretch 9.12 and updated the [instructions](https://handbrake.fr/docs/en/latest/developer/install-dependencies-debian.html) accordingly ([1.3.x](https://handbrake.fr/docs/en/1.3.0/developer/install-dependencies-debian.html) also) in 44c42a10b5299a7d39832da08d80c691b86bd54f. Will be published soon. Thanks for the heads up!
